spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file://Users/Guest/Microservices/src/main/resources/config-files/{application}/{profile},
            file://Users/Guest/Microservices/src/main/resources/config-files/global/{profile}